---
# pre-commit install --allow-missing-config
# pre-commit autoupdate
# pre-commit run --all-files --color auto
exclude: |
  (?x)^(
    \.pre-commit-config\.yaml$
  )
fail_fast: true
default_stages:
  - pre-commit
default_install_hook_types:
  - commit-msg
  - pre-commit
repos:
  - repo: meta
    hooks:
      - id: identity
        name: "meta | pre-commit hooks"
        stages:
          - manual
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.1
    hooks:
      - id: commitizen
        name: "commitizen | validate commit messages"
        stages:
          - commit-msg
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        name: "git | block large files"
        args: [--maxkb=2048]
      - id: check-json
        name: "general | check JSON files"
      - id: end-of-file-fixer
        name: "general | fix end of file"
      - id: mixed-line-ending
        name: "general | fix line ending"
        args:
          - --fix=auto
      - id: trailing-whitespace
        name: "general | remove trailing whitespace"
      - id: pretty-format-json
        name: "general | prettify JSON files"
        args:
          - --autofix
          - --no-ensure-ascii
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        name: "md | lint: run markdownlint-cli"
        args:
          - --config
          - .config/.markdown-lint.yml
        exclude: |
          (?x)
          ^.github/instructions/.*|
          ^CHANGELOG.md|
          ^README.md
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        name: "yaml | lint: run yamllint"
        args:
          - -c
          - .config/.yaml-lint.yml
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.18
    hooks:
      - id: uv-export
        name: "python | uv: export dependencies"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        name: "python | lint: run ruff-check"
        args:
          - --fix
        files: "\\.py$"
        exclude: |
          (?x)
          ^tests/.*
        stages:
          - manual
      - id: ruff-format
        name: "python | lint: run ruff-format"
        files: "\\.py$"
        exclude: |
          (?x)
          ^tests/.*
        stages:
          - manual
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        name: "python | code: run pyupgrade"
        args:
          - --py310
        stages:
          - manual
  - repo: https://github.com/asottile/dead
    rev: v2.1.0
    hooks:
      - id: dead
        name: "python | code: check for dead"
        exclude: |
          (?x)
          ^install/.*
        stages:
          - manual
  - repo: local
    hooks:
      - id: pin-github-action
        name: "security | gh-action: pinned sha"
        verbose: true
        files: ^\.github/workflows/[^/]+\.ya?ml$
        entry: "pin-github-action ."
        args:
          - --allow
          - "mighty-muffin/*"
        language: node
        additional_dependencies:
          - pin-github-action@3.4.0
        stages:
          - manual
