---
site_name: Insecure Banking Documentation
site_description: Documentation for the Insecure Banking application
site_author: Mighty Muffin

docs_dir: docs

theme:
  name: material
  palette:
    scheme: slate
  features:
    # - navigation.tabs
    # - navigation.sections
    # - toc.integrated
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes:

nav:
  - Home: README.md
  - Project Overview: project-overview.md
  - Development:
      - Setup: development/setup.md
      - Running: development/running.md
      - Docker: development/docker.md
      - Dependencies: development/dependencies.md
      - Code Quality: development/quality.md
      - Contributing: development/contributing.md
  - Architecture:
      - Overview: architecture/overview.md
      - Database: architecture/db.md
      - Middleware: architecture/middleware.md
  - Testing:
      - Overview: testing/overview.md
  - Security:
      - Overview: security/overview.md
      - Iditarod: security/iditarod.md
