---
name: CI - Branches

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - demo/*
      - dev
      - feat/*
      - fix/*
      - rel/*
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  branch:
    name: Branch Workflow
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install UV
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: 0.9.18

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: "3.10"

      - name: Install dependencies for scanning
        run: |
          echo "Using requirements.txt for ease of compatibility."
          uv venv .venv --python 3.10
          uv pip install --no-cache-dir -r requirements.txt
        shell: bash

      - name: Run SAST
        id: sast
        run: |
          echo Run SAST
          echo "::warning::Must implement a code scanning mechanism."
        shell: bash
