---
name: CI - PR

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:

  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run Pre-Commit Checks
        uses: j178/prek-action@91fd7d7cf70ae1dee9f4f44e7dfa5d1073fe6623 # v1.0.11
        env:
          SKIP: "pytest, pin-github-action"

  secret:
    needs:
      - pre-commit
    name: Secret Scanning
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: GitGuardian scan
        id: ggshield_scan
        uses: GitGuardian/ggshield/actions/secret@edac2af7a4c4670e24600482e6ae0b3e2bb52160 # v1.45.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        continue-on-error: true

      - name: Check status of potentially failing step and issue warning
        if: steps.ggshield_scan.outcome == 'failure'
        run: |
          echo "::error::The previous step detected potential secrets in the code. Please review the scan report above."
        shell: bash

  code_build:
    needs:
      - pre-commit
    name: Build & Unit Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, ubuntu-24.04, ubuntu-24.04-arm]
        python-version: ["3.10"]
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install UV
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: 0.9.18

      - name: Setup Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev --frozen
        shell: bash

      - name: Pytest - Run Unit Test
        continue-on-error: true
        run: |
          uv run pytest
        shell: bash

      - name: Minimize UV cache
        run: |
          uv cache prune --ci
        shell: bash

  code_scan:
    needs:
      - pre-commit
    name: Vulnerabilities Scan
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install UV
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: 0.9.18

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: "3.10"

      - name: Run SAST
        id: sast
        run: |
          echo Run SAST
        shell: bash

      - name: Run SCA
        id: sca
        run: |
          echo Run SCA
        shell: bash

      - name: Check status of potentially failing step and issue warning
        if: steps.sast.outcome == 'failure' || steps.sca.outcome == 'failure'
        run: |
          echo "::error::The previous step detected potential vulnerabilities in the code. Please review the scan report above."
          exit 1
        shell: bash

  docker_build:
    needs:
      - code_build
    name: Container Build
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
          tags: |
            type=raw,value=latest,enable={{is_default_branch}},priority=100
            type=ref,event=branch,priority=100
            type=raw,value=gha-${{ github.run_id }},enable=${{github.event_name == 'pull_request'}},priority=200
            type=raw,value=nightly-${{ github.run_id }},enable=${{github.event_name == 'schedule'}},priority=200
            type=ref,event=pr,priority=200
            type=ref,event=tag,priority=200
            type=sha,value={{sha}},enable={{is_default_branch}},priority=300

      - name: Docker Build
        id: build_image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          platforms: |
            linux/amd64
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            GIT_COMMIT=${{ github.sha }}
            REPO_URL=${{ github.server_url }}/${{ github.repository }}

      - name: Find the primary image tag we just pushed, and output it
        id: image-tag
        run: |
          # shellcheck disable=SC2086
          echo "image-tag=${{ steps.docker_meta.outputs.version }}" >> $GITHUB_OUTPUT
        shell: bash

  docker_scan:
    needs:
      - docker_build
    name: Container Vulnerability Scan
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Run Container Scan
        id: container
        run: |
          echo Run Container Scan
        shell: bash

      - name: Check status of potentially failing step and issue warning
        if: steps.container.outcome == 'failure'
        run: |
          echo "::error::The previous step detected potential vulnerabilities in the code. Please review the scan report above."
          exit 1
        shell: bash

  gating:
    needs:
      - code_scan
      - docker_scan
      - secret
    name: Gating
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:

      - name: Run Gating Check
        run: echo Run Gating Check
        shell: bash
