---
name: CI - Tag

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  release:
    name: Semantic Release
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    outputs:
      notes: ${{ steps.generate_notes.outputs.notes }}

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: 3.14

      - name: Get Version
        id: tag_name
        run: |
          echo "current_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Get CHANGELOG
        id: generate_notes
        uses: anmarkoulis/commitizen-changelog-reader@0d1f06b1c3de81073cf4168c227268c6dd2bfa04 # v1.2.0
        with:
          tag_name: ${{ github.ref }}
          changelog: CHANGELOG.md

      - name: Update CHANGELOG
        run: |
          echo "${{join(fromJson(steps.generate_notes.outputs.notes).notes, '')}}" > ${{ github.workspace }}-GH_CHANGELOG.md

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        if: github.ref_type == 'tag'
        with:
          body_path: ${{ github.workspace }}-GH_CHANGELOG.md
          repository: ${{ github.repository }}
          token: ${{ secrets.RELEASE_PAT }}
